//! The public protocol surface for `mpv-targets`.
//!
//! This crate deliberately owns the wire types used by both the daemon and its
//! clients.  Keeping the model here makes it impossible for the operator client
//! to acquire a private daemon protocol.

pub mod answer;
pub mod client;
pub mod config;
pub mod protocol;
mod tls;

pub use answer::{AnswerError, AnswerFile, AnswerTarget, AnswerTls, ServiceAnswer};
pub use client::{
    ClientError, ClientOptions, LoadMode, LoopState, RemoteClient, TargetClient, Track,
};

/// The ordinary target baseline used when no source configuration is supplied.
pub fn base_mpv_conf(start_paused: bool, start_muted: bool, volume: f64) -> String {
    format!(
        "# Generated by mpv-targets. Edit this target-local file for advanced mpv settings.\nforce-window=yes\nidle=yes\nreally-quiet=yes\npause={}\nvolume={}\nmute={}\ndirectory-mode=recursive\n",
        if start_paused { "yes" } else { "no" },
        volume,
        if start_muted { "yes" } else { "no" },
    )
}
pub use config::{ConfigError, DaemonConfig, TargetConfig, TlsConfig};
pub use protocol::{
    ErrorCode, ErrorResponse, Event, Health, HealthState, MpvOperation, Operation, Request,
    Response, ServiceOperation, Snapshot, TargetChanged, TargetRecord, TargetState,
};
pub use tls::{TlsMaterialError, server_tls_config};
